import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../styles/global.css";
import { Providers } from "./providers";
import HeaderNavigation from "@/components/header-navigartion";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased dark",
          fontSans.variable
        )}
      >
        <Providers>
          <HeaderNavigation />
          <main className="pt-16">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
